name: Coverage export

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Generate coverage
        run: npm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
